channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.12
  - pip:
    - pvlib==0.10.2
    - numpy==1.26.2
    - matplotlib==3.8.2
    - pandas==2.1.3
    - myst_nb==0.17.1
    - sphinx
    - ablog==0.11.6
    - sphinxcontrib-bibtex
    - sphinxext-opengraph
    - sphinx-panels
    - pydata-sphinx-theme==0.14.4
    - folium
    - xarray
    - lxml
    - rich
