channels:
    - defaults
    - conda-forge
dependencies:
    - scipy
    - numpy
    - matplotlib
    - pandas
    - sphinx
    - folium
    - xarray
    - cartopy
    - pip
        - git+https://git@github.com/pvlib/pvlib-python@master#egg=pvlib
        - myst_nb
        - ablog
        - sphinxcontrib-bibtex
        - sphinxext-opengraph
        - sphinx-panels
        - pydata-sphinx-theme
